#web
server:
  port: 8900
#  context-path: /cyl

### resources
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  ### cyl-job, datasource
  datasource:
    primary: #数据源1-提供给当前系统使用
      url: jdbc:mysql://127.0.0.1:3306/xxl_job?Unicode=true&useSSL=false&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    secondary: #数据源2-提供给job使用，有些job可能会去调用其他数据库
      url: jdbc:oracle:thin:@192.168.1.100:1523:XE
      username: loan
      password: loan
      driverClassName: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 50
        minimum-idle: 10
        auto-commit: true
        read-only: false
        connection-timeout: 60000
        idle-timeout: 60000
        validation-timeout: 3000
        max-lifetime: 60000
        login-timeout: 5

  ### freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  mail:
    host: smtp.qq.com
    port: 25
    username: 1072223954@qq.com
    password:
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true 
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
### mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis-mappers/*Mapper.xml
  typeAliasesPackage: com.cyl.api.model



trigger:
  timeout: 500
cyl:
  job:
    accessToken:
    i18n:  
  mail:
    username: